export const africanCountryCodes = [
  { code: "+243", country: "DR Congo" },
  { code: "+237", country: "Cameroon" },
  { code: "+234", country: "Nigeria" },
  { code: "+233", country: "Ghana" },
  { code: "+221", country: "Senegal" },
  { code: "+213", country: "Algeria" },
  { code: "+244", country: "Angola" },
  { code: "+267", country: "Botswana" },
  { code: "+238", country: "Cape Verde" },
  { code: "+236", country: "Central African Republic" },
  { code: "+235", country: "Chad" },
  { code: "+242", country: "Congo" },
  { code: "+253", country: "Djibouti" },
  { code: "+20", country: "Egypt" },
  { code: "+240", country: "Equatorial Guinea" },
  { code: "+251", country: "Ethiopia" },
  { code: "+241", country: "Gabon" },
  { code: "+220", country: "Gambia" },
  { code: "+224", country: "Guinea" },
  { code: "+245", country: "Guinea-Bissau" },
  { code: "+225", country: "Ivory Coast" },
  { code: "+254", country: "Kenya" },
  { code: "+266", country: "Lesotho" },
  { code: "+231", country: "Liberia" },
  { code: "+218", country: "Libya" },
  { code: "+261", country: "Madagascar" },
  { code: "+265", country: "Malawi" },
  { code: "+223", country: "Mali" },
  { code: "+222", country: "Mauritania" },
  { code: "+230", country: "Mauritius" },
  { code: "+212", country: "Morocco" },
  { code: "+258", country: "Mozambique" },
  { code: "+264", country: "Namibia" },
  { code: "+227", country: "Niger" },
  { code: "+250", country: "Rwanda" },
  { code: "+239", country: "Sao Tome and Principe" },
  { code: "+248", country: "Seychelles" },
  { code: "+232", country: "Sierra Leone" },
  { code: "+252", country: "Somalia" },
  { code: "+27", country: "South Africa" },
  { code: "+211", country: "South Sudan" },
  { code: "+249", country: "Sudan" },
  { code: "+268", country: "Swaziland" },
  { code: "+255", country: "Tanzania" },
  { code: "+228", country: "Togo" },
  { code: "+216", country: "Tunisia" },
  { code: "+256", country: "Uganda" },
  { code: "+260", country: "Zambia" },
  { code: "+263", country: "Zimbabwe" }
];